### ISSUE TITLE
Undefined function or variable 'skew'.

### ISSUE THREAD

**Issue by Yanzqing** [jbriales/corner-calib#2]
When i run the demo, error occurs!
Undefined function or variable 'skew'.
Error in reprojectLaserCalib (line 41)
    L(4:6,:) = -skew([0;0;10]) \* LrsPts;
Error in optimizeLaserCamCalib (line 37)
    y                = reprojectLaserCalib(x0,xdata);
Error in lccMinSol (line 71)
    [T, r, ri] = optimizeLaserCamCalib(Ti, Tp(:,:,inl), Pl(inl));
Error in demo (line 22)
[T, r, inl, Ti, ri] = lccMinSol(Planes, Points,T_set);
Can you offer the function skew? Thank you!

**Comment by jbriales** [comment]
The commit 834fc96419f8d2838a3726399de07505f5a0e660 should fix this.
Anyway, I and my colleague didn't have the time to polish this project as much as we would have liked. If you find more missing dependencies, maybe you can look at my collection of common math functions in [Mmath](https://github.com/jesusbriales/Mmath).
